### PR TITLE
Update DataLoader.py

### PR DESCRIPTION
**Pull request by Anirudh257**
Made changes to self.train_index as the earlier code showed **range error**

### CODE REVIEW

**Comment by FesianXu** [comment]
your code is more compact and seems same effect. But i don't understand why it will cause `range error`. Could you please give me more details?

**Comment by Anirudh257** [comment]
So, I was running your code on my system and I got this error when **range** function was present:
image

This might be due to some version changes.

**Comment by FesianXu** [comment]
It's exactly the version problem.
In fact, in python3, the output of `range()` will not be a list, which will cause this unexpected error. we just add a `list(range(length))` to wrap the range then the bug should be fixed. And yes, give me some time , i will fix it when i'm free.
Also, I have tried your pulled code. But it seems that `np.random.randint()` just generates a random int number instead of the random order list, which is not suitable here.

**Comment by Anirudh257** [comment]
Okay, I will make the changes as suggested. I have made another pull request doing what you have suggested above.

**Pull request closed without merging**
